variable "region" {}
variable "vpc_cidr" {}
variable "private_subnets_cidr" {}
variable "public_subnets_cidr" {}
variable "private_subnets_names" {}
variable "public_subnets_names" {}
variable "vpc_name" {}
variable "igw_name" {}
variable "ami" {}
variable "volume_size" {}
variable "ssh_key" {}
variable "ec2_types" {}
variable "ec2_names" {}
variable "worker_nodes_types" {}
variable "group_nodes_name" {}
variable "max_nodes" {}
variable "min_nodes" {}
variable "desired_nodes" {}
variable "k8s_version" {}
variable "cluster_name" {}
variable "ecr_name" {}